# Generated by Django 5.0.6 on 2024-05-26 08:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChaiVariety",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="chais/")),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "types",
                    models.CharField(
                        choices=[
                            ("ML", "Masala Chai"),
                            ("BL", "Black Chai"),
                            ("WL", "White Chai"),
                            ("SL", "Sweet Chai"),
                            ("CL", "Coffee Chai"),
                            ("GL", "Green Chai"),
                        ],
                        max_length=2,
                    ),
                ),
            ],
        ),
    ]
