# Generated by Django 5.0.6 on 2024-05-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chai", "0002_chaivariety_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="chaivariety",
            name="pricing",
            field=models.CharField(default="0", max_length=5),
        ),
    ]
