# Generated by Django 5.0.6 on 2024-05-26 09:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chai", "0003_chaivariety_pricing"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chaivariety",
            old_name="pricing",
            new_name="price",
        ),
    ]
